# Generated by Django 4.2.1 on 2023-05-30 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('model', models.CharField(max_length=50, verbose_name='Модель')),
                ('release_date', models.DateField(verbose_name='Дата выпуска')),
            ],
            options={
                'verbose_name': ('Товар',),
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.PositiveSmallIntegerField(choices=[(1, 'Завод'), (2, 'Розничная сеть'), (3, 'Индивидуальный предприниматель')], verbose_name='Тип поставщика')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('email', models.EmailField(max_length=254, verbose_name='Почта')),
                ('country', models.CharField(max_length=20, verbose_name='Страна')),
                ('city', models.CharField(max_length=20, verbose_name='Город')),
                ('street_name', models.CharField(max_length=50, verbose_name='Улица')),
                ('building_number', models.CharField(max_length=6, verbose_name='Номер дома')),
            ],
            options={
                'verbose_name': ('Поставщик',),
                'verbose_name_plural': 'Поставщики',
            },
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название')),
                ('level', models.PositiveIntegerField(default=0, verbose_name='Уровень звена')),
                ('indebtedness', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Задолженность')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('previous_node', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='api.node', verbose_name='Предыдущее звено')),
                ('products', models.ManyToManyField(to='api.product', verbose_name='Товары')),
                ('supplier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nodes', to='api.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': ('Звено',),
                'verbose_name_plural': 'Звенья',
            },
        ),
    ]
