# Generated by Django 4.2.1 on 2023-05-31 19:31

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('country', models.CharField(max_length=20, verbose_name='Страна')),
                ('city', models.CharField(max_length=20, verbose_name='Город')),
                ('street_name', models.CharField(max_length=50, verbose_name='Улица')),
                ('building_number', models.CharField(max_length=6, verbose_name='Номер дома')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Звено', 'verbose_name_plural': 'Звенья'},
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='building_number',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='city',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='country',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='email',
        ),
        migrations.RemoveField(
            model_name='supplier',
            name='street_name',
        ),
        migrations.AddField(
            model_name='supplier',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='supplier',
            name='indebtedness',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True, verbose_name='Задолженность'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='level',
            field=models.PositiveIntegerField(default=0, verbose_name='Уровень звена'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='api.product', verbose_name='Товары'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='api.supplier', verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Завод'), (2, 'Розничная сеть'), (3, 'Индивидуальный предприниматель')], verbose_name='Тип звена'),
        ),
        migrations.DeleteModel(
            name='Node',
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='api.contact', verbose_name='Контакты'),
        ),
    ]
