# Generated by Django 4.2.1 on 2023-06-01 19:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_contact_alter_product_options_alter_supplier_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supplier',
            options={'verbose_name': 'Участник', 'verbose_name_plural': 'Участники'},
        ),
        migrations.AlterField(
            model_name='supplier',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='api.contact', verbose_name='Контакты'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Завод'), (2, 'Розничная сеть'), (3, 'Индивидуальный предприниматель')], verbose_name='Тип'),
        ),
    ]
