# Generated by Django 4.2.1 on 2023-06-01 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_supplier_options_alter_supplier_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='products',
            field=models.ManyToManyField(to='api.product', verbose_name='Товары'),
        ),
    ]
