# Generated by Django 4.2.1 on 2023-06-04 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_supplier_products'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='building_number',
            field=models.CharField(blank=True, max_length=6, null=True, verbose_name='Номер дома'),
        ),
    ]
