# Generated by Django 4.2.1 on 2023-06-04 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_contact_city_alter_contact_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, to='api.product', verbose_name='Товары'),
        ),
    ]
