# Generated by Django 4.2.1 on 2023-06-04 17:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_supplier_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suppliers', to='api.supplier', verbose_name='Поставщик'),
        ),
    ]
